
- name: Deploy Weather-Wardrobe App
  hosts: weather_host
  become: true

  tasks:
    - name: Remove conflicting containerd package
      apt:
        name: containerd
        state: absent
      ignore_errors: true

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up Docker stable repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Update apt and install Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: pratheep2006/weather-wardrobe
        source: pull

    - name: Run the container
      docker_container:
        name: weather-wardrobe
        image: pratheep2006/weather-wardrobe
        state: started
        restart_policy: always
        ports:
          - "8001:8080"

